<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/preliminaries.php");
	include("$currDir/preliminaries_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('preliminaries');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "preliminaries";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`preliminaries`.`id`" => "id",
		"`preliminaries`.`team`" => "team",
		"`preliminaries`.`matches`" => "matches",
		"`preliminaries`.`wins`" => "wins",
		"`preliminaries`.`losses`" => "losses",
		"`preliminaries`.`draws`" => "draws",
		"`preliminaries`.`points`" => "points",
		"`preliminaries`.`created_by`" => "created_by",
		"`preliminaries`.`edited_by`" => "edited_by"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`preliminaries`.`id`',
		2 => '`preliminaries`.`team`',
		3 => '`preliminaries`.`matches`',
		4 => '`preliminaries`.`wins`',
		5 => '`preliminaries`.`losses`',
		6 => '`preliminaries`.`draws`',
		7 => '`preliminaries`.`points`',
		8 => 8,
		9 => 9
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`preliminaries`.`id`" => "id",
		"`preliminaries`.`team`" => "team",
		"`preliminaries`.`matches`" => "matches",
		"`preliminaries`.`wins`" => "wins",
		"`preliminaries`.`losses`" => "losses",
		"`preliminaries`.`draws`" => "draws",
		"`preliminaries`.`points`" => "points",
		"`preliminaries`.`created_by`" => "created_by",
		"`preliminaries`.`edited_by`" => "edited_by"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`preliminaries`.`id`" => "ID",
		"`preliminaries`.`team`" => "Team",
		"`preliminaries`.`matches`" => "Matches",
		"`preliminaries`.`wins`" => "Wins",
		"`preliminaries`.`losses`" => "Losses",
		"`preliminaries`.`draws`" => "Draws",
		"`preliminaries`.`points`" => "Points",
		"`preliminaries`.`created_by`" => "Created by",
		"`preliminaries`.`edited_by`" => "Edited by"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`preliminaries`.`id`" => "id",
		"`preliminaries`.`team`" => "team",
		"`preliminaries`.`matches`" => "matches",
		"`preliminaries`.`wins`" => "wins",
		"`preliminaries`.`losses`" => "losses",
		"`preliminaries`.`draws`" => "draws",
		"`preliminaries`.`points`" => "points",
		"`preliminaries`.`created_by`" => "created_by",
		"`preliminaries`.`edited_by`" => "edited_by"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`preliminaries` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "preliminaries_view.php";
	$x->RedirectAfterInsert = "preliminaries_view.php?SelectedID=#ID#";
	$x->TableTitle = "Preliminaries";
	$x->TableIcon = "resources/table_icons/traffic_lights_green.png";
	$x->PrimaryKey = "`preliminaries`.`id`";
	$x->DefaultSortField = '7';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Team", "Matches", "Wins", "Losses", "Draws", "Points", "Created by", "Edited by");
	$x->ColFieldName = array('team', 'matches', 'wins', 'losses', 'draws', 'points', 'created_by', 'edited_by');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9);

	// template paths below are based on the app main directory
	$x->Template = 'templates/preliminaries_templateTV.html';
	$x->SelectedTemplate = 'templates/preliminaries_templateTVS.html';
	$x->TemplateDV = 'templates/preliminaries_templateDV.html';
	$x->TemplateDVP = 'templates/preliminaries_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `preliminaries`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='preliminaries' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `preliminaries`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='preliminaries' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`preliminaries`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: preliminaries_init
	$render=TRUE;
	if(function_exists('preliminaries_init')){
		$args=array();
		$render=preliminaries_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: preliminaries_header
	$headerCode='';
	if(function_exists('preliminaries_header')){
		$args=array();
		$headerCode=preliminaries_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: preliminaries_footer
	$footerCode='';
	if(function_exists('preliminaries_footer')){
		$args=array();
		$footerCode=preliminaries_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>