<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/role_types.php");
	include("$currDir/role_types_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('role_types');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "role_types";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`role_types`.`id`" => "id",
		"`role_types`.`role_type`" => "role_type",
		"`role_types`.`created_by`" => "created_by",
		"`role_types`.`edited_by`" => "edited_by"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`role_types`.`id`',
		2 => 2,
		3 => 3,
		4 => 4
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`role_types`.`id`" => "id",
		"`role_types`.`role_type`" => "role_type",
		"`role_types`.`created_by`" => "created_by",
		"`role_types`.`edited_by`" => "edited_by"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`role_types`.`id`" => "ID",
		"`role_types`.`role_type`" => "Role Type",
		"`role_types`.`created_by`" => "Created by",
		"`role_types`.`edited_by`" => "Edited by"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`role_types`.`id`" => "id",
		"`role_types`.`role_type`" => "role_type",
		"`role_types`.`created_by`" => "created_by",
		"`role_types`.`edited_by`" => "edited_by"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`role_types` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 0;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "role_types_view.php";
	$x->RedirectAfterInsert = "role_types_view.php?SelectedID=#ID#";
	$x->TableTitle = "Role Types";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`role_types`.`id`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Role Type", "Created by", "Edited by");
	$x->ColFieldName = array('role_type', 'created_by', 'edited_by');
	$x->ColNumber  = array(2, 3, 4);

	// template paths below are based on the app main directory
	$x->Template = 'templates/role_types_templateTV.html';
	$x->SelectedTemplate = 'templates/role_types_templateTVS.html';
	$x->TemplateDV = 'templates/role_types_templateDV.html';
	$x->TemplateDVP = 'templates/role_types_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `role_types`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='role_types' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `role_types`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='role_types' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`role_types`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: role_types_init
	$render=TRUE;
	if(function_exists('role_types_init')){
		$args=array();
		$render=role_types_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: role_types_header
	$headerCode='';
	if(function_exists('role_types_header')){
		$args=array();
		$headerCode=role_types_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: role_types_footer
	$footerCode='';
	if(function_exists('role_types_footer')){
		$args=array();
		$footerCode=role_types_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>