<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/roles.php");
	include("$currDir/roles_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('roles');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "roles";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`roles`.`id`" => "id",
		"`roles`.`role`" => "role",
		"IF(    CHAR_LENGTH(`role_types1`.`role_type`), CONCAT_WS('',   `role_types1`.`role_type`), '') /* Role Type */" => "role_type",
		"`roles`.`created_by`" => "created_by",
		"`roles`.`edited_by`" => "edited_by"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`roles`.`id`',
		2 => 2,
		3 => '`role_types1`.`role_type`',
		4 => 4,
		5 => 5
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`roles`.`id`" => "id",
		"`roles`.`role`" => "role",
		"IF(    CHAR_LENGTH(`role_types1`.`role_type`), CONCAT_WS('',   `role_types1`.`role_type`), '') /* Role Type */" => "role_type",
		"`roles`.`created_by`" => "created_by",
		"`roles`.`edited_by`" => "edited_by"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`roles`.`id`" => "ID",
		"`roles`.`role`" => "Role",
		"IF(    CHAR_LENGTH(`role_types1`.`role_type`), CONCAT_WS('',   `role_types1`.`role_type`), '') /* Role Type */" => "Role Type",
		"`roles`.`created_by`" => "Created by",
		"`roles`.`edited_by`" => "Edited by"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`roles`.`id`" => "id",
		"`roles`.`role`" => "role",
		"IF(    CHAR_LENGTH(`role_types1`.`role_type`), CONCAT_WS('',   `role_types1`.`role_type`), '') /* Role Type */" => "role_type",
		"`roles`.`created_by`" => "created_by",
		"`roles`.`edited_by`" => "edited_by"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'role_type' => 'Role Type');

	$x->QueryFrom = "`roles` LEFT JOIN `role_types` as role_types1 ON `role_types1`.`id`=`roles`.`role_type` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 0;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "roles_view.php";
	$x->RedirectAfterInsert = "roles_view.php?SelectedID=#ID#";
	$x->TableTitle = "Roles";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`roles`.`id`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("Role", "Role Type", "Created by", "Edited by");
	$x->ColFieldName = array('role', 'role_type', 'created_by', 'edited_by');
	$x->ColNumber  = array(2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/roles_templateTV.html';
	$x->SelectedTemplate = 'templates/roles_templateTVS.html';
	$x->TemplateDV = 'templates/roles_templateDV.html';
	$x->TemplateDVP = 'templates/roles_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `roles`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='roles' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `roles`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='roles' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`roles`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: roles_init
	$render=TRUE;
	if(function_exists('roles_init')){
		$args=array();
		$render=roles_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: roles_header
	$headerCode='';
	if(function_exists('roles_header')){
		$args=array();
		$headerCode=roles_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: roles_footer
	$footerCode='';
	if(function_exists('roles_footer')){
		$args=array();
		$footerCode=roles_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>