<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/teams.php");
	include("$currDir/teams_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('teams');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "teams";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`teams`.`id`" => "id",
		"`teams`.`team_logo`" => "team_logo",
		"`teams`.`team_name`" => "team_name",
		"IF(    CHAR_LENGTH(`schools1`.`school_name`), CONCAT_WS('',   `schools1`.`school_name`), '') /* School */" => "school",
		"`teams`.`matches`" => "matches",
		"`teams`.`wins`" => "wins",
		"`teams`.`losses`" => "losses",
		"`teams`.`draws`" => "draws",
		"`teams`.`points`" => "points",
		"`teams`.`created_by`" => "created_by",
		"`teams`.`edited_by`" => "edited_by"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`teams`.`id`',
		2 => 2,
		3 => 3,
		4 => '`schools1`.`school_name`',
		5 => '`teams`.`matches`',
		6 => '`teams`.`wins`',
		7 => '`teams`.`losses`',
		8 => '`teams`.`draws`',
		9 => '`teams`.`points`',
		10 => 10,
		11 => 11
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`teams`.`id`" => "id",
		"`teams`.`team_logo`" => "team_logo",
		"`teams`.`team_name`" => "team_name",
		"IF(    CHAR_LENGTH(`schools1`.`school_name`), CONCAT_WS('',   `schools1`.`school_name`), '') /* School */" => "school",
		"`teams`.`matches`" => "matches",
		"`teams`.`wins`" => "wins",
		"`teams`.`losses`" => "losses",
		"`teams`.`draws`" => "draws",
		"`teams`.`points`" => "points",
		"`teams`.`created_by`" => "created_by",
		"`teams`.`edited_by`" => "edited_by"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`teams`.`id`" => "ID",
		"`teams`.`team_name`" => "Team Name",
		"IF(    CHAR_LENGTH(`schools1`.`school_name`), CONCAT_WS('',   `schools1`.`school_name`), '') /* School */" => "School",
		"`teams`.`matches`" => "Matches",
		"`teams`.`wins`" => "Wins",
		"`teams`.`losses`" => "Losses",
		"`teams`.`draws`" => "Draws",
		"`teams`.`points`" => "Points",
		"`teams`.`created_by`" => "Created by",
		"`teams`.`edited_by`" => "Edited by"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`teams`.`id`" => "id",
		"`teams`.`team_name`" => "team_name",
		"IF(    CHAR_LENGTH(`schools1`.`school_name`), CONCAT_WS('',   `schools1`.`school_name`), '') /* School */" => "school",
		"`teams`.`matches`" => "matches",
		"`teams`.`wins`" => "wins",
		"`teams`.`losses`" => "losses",
		"`teams`.`draws`" => "draws",
		"`teams`.`points`" => "points",
		"`teams`.`created_by`" => "created_by",
		"`teams`.`edited_by`" => "edited_by"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'school' => 'School');

	$x->QueryFrom = "`teams` LEFT JOIN `schools` as schools1 ON `schools1`.`id`=`teams`.`school` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "teams_view.php";
	$x->RedirectAfterInsert = "teams_view.php?SelectedID=#ID#";
	$x->TableTitle = "Teams";
	$x->TableIcon = "resources/table_icons/group.png";
	$x->PrimaryKey = "`teams`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Team Logo", "Team Name", "School", "Matches", "Wins", "Losses", "Draws", "Points", "Created by");
	$x->ColFieldName = array('team_logo', 'team_name', 'school', 'matches', 'wins', 'losses', 'draws', 'points', 'created_by');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10);

	// template paths below are based on the app main directory
	$x->Template = 'templates/teams_templateTV.html';
	$x->SelectedTemplate = 'templates/teams_templateTVS.html';
	$x->TemplateDV = 'templates/teams_templateDV.html';
	$x->TemplateDVP = 'templates/teams_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `teams`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='teams' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `teams`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='teams' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`teams`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: teams_init
	$render=TRUE;
	if(function_exists('teams_init')){
		$args=array();
		$render=teams_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: teams_header
	$headerCode='';
	if(function_exists('teams_header')){
		$args=array();
		$headerCode=teams_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: teams_footer
	$footerCode='';
	if(function_exists('teams_footer')){
		$args=array();
		$footerCode=teams_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>