<?php

// Data functions (insert, update, delete, form) for table teams

// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

function teams_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('teams');
	if(!$arrPerm[1]){
		return false;
	}

	$data['team_name'] = makeSafe($_REQUEST['team_name']);
		if($data['team_name'] == empty_lookup_value){ $data['team_name'] = ''; }
	$data['school'] = makeSafe($_REQUEST['school']);
		if($data['school'] == empty_lookup_value){ $data['school'] = ''; }
	$data['matches'] = makeSafe($_REQUEST['matches']);
		if($data['matches'] == empty_lookup_value){ $data['matches'] = ''; }
	$data['wins'] = makeSafe($_REQUEST['wins']);
		if($data['wins'] == empty_lookup_value){ $data['wins'] = ''; }
	$data['losses'] = makeSafe($_REQUEST['losses']);
		if($data['losses'] == empty_lookup_value){ $data['losses'] = ''; }
	$data['draws'] = makeSafe($_REQUEST['draws']);
		if($data['draws'] == empty_lookup_value){ $data['draws'] = ''; }
	$data['points'] = makeSafe($_REQUEST['points']);
		if($data['points'] == empty_lookup_value){ $data['points'] = ''; }
	$data['created_by'] = parseCode('<%%creatorUsername%%>', true);
	$data['team_logo'] = PrepareUploadedFile('team_logo', 102400,'jpg|jpeg|gif|png', false, '');
	if($data['team_logo']) createThumbnail($data['team_logo'], getThumbnailSpecs('teams', 'team_logo', 'tv'));
	if($data['team_logo']) createThumbnail($data['team_logo'], getThumbnailSpecs('teams', 'team_logo', 'dv'));
	if($data['team_name']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Team Name': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['school']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'School': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['matches'] == '') $data['matches'] = "0";
	if($data['wins'] == '') $data['wins'] = "0";
	if($data['losses'] == '') $data['losses'] = "0";
	if($data['draws'] == '') $data['draws'] = "0";
	if($data['points'] == '') $data['points'] = "0";

	/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
	if($_REQUEST['SelectedID']){
		$res = sql("select * from teams where id='" . makeSafe($_REQUEST['SelectedID']) . "'", $eo);
		if($row = db_fetch_assoc($res)){
			if(!$data['team_logo']) $data['team_logo'] = makeSafe($row['team_logo']);
		}
	}

	// hook: teams_before_insert
	if(function_exists('teams_before_insert')){
		$args=array();
		if(!teams_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `teams` set       ' . ($data['team_logo'] != '' ? "`team_logo`='{$data['team_logo']}'" : '`team_logo`=NULL') . ', `team_name`=' . (($data['team_name'] !== '' && $data['team_name'] !== NULL) ? "'{$data['team_name']}'" : 'NULL') . ', `school`=' . (($data['school'] !== '' && $data['school'] !== NULL) ? "'{$data['school']}'" : 'NULL') . ', `matches`=' . (($data['matches'] !== '' && $data['matches'] !== NULL) ? "'{$data['matches']}'" : 'NULL') . ', `wins`=' . (($data['wins'] !== '' && $data['wins'] !== NULL) ? "'{$data['wins']}'" : 'NULL') . ', `losses`=' . (($data['losses'] !== '' && $data['losses'] !== NULL) ? "'{$data['losses']}'" : 'NULL') . ', `draws`=' . (($data['draws'] !== '' && $data['draws'] !== NULL) ? "'{$data['draws']}'" : 'NULL') . ', `points`=' . (($data['points'] !== '' && $data['points'] !== NULL) ? "'{$data['points']}'" : 'NULL') . ', `created_by`=' . "'{$data['created_by']}'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"teams_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: teams_after_insert
	if(function_exists('teams_after_insert')){
		$res = sql("select * from `teams` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!teams_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('teams', $recID, getLoggedMemberID());

	return $recID;
}

function teams_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('teams');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='teams' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='teams' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: teams_before_delete
	if(function_exists('teams_before_delete')){
		$args=array();
		if(!teams_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: students
	$res = sql("select `id` from `teams` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `students` where `team`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "students", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "students", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='teams_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='teams_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `teams` where `id`='$selected_id'", $eo);

	// hook: teams_after_delete
	if(function_exists('teams_after_delete')){
		$args=array();
		teams_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='teams' and pkValue='$selected_id'", $eo);
}

function teams_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('teams');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='teams' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='teams' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['team_name'] = makeSafe($_REQUEST['team_name']);
		if($data['team_name'] == empty_lookup_value){ $data['team_name'] = ''; }
	if($data['team_name']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Team Name': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['school'] = makeSafe($_REQUEST['school']);
		if($data['school'] == empty_lookup_value){ $data['school'] = ''; }
	if($data['school']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'School': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['matches'] = makeSafe($_REQUEST['matches']);
		if($data['matches'] == empty_lookup_value){ $data['matches'] = ''; }
	$data['wins'] = makeSafe($_REQUEST['wins']);
		if($data['wins'] == empty_lookup_value){ $data['wins'] = ''; }
	$data['losses'] = makeSafe($_REQUEST['losses']);
		if($data['losses'] == empty_lookup_value){ $data['losses'] = ''; }
	$data['draws'] = makeSafe($_REQUEST['draws']);
		if($data['draws'] == empty_lookup_value){ $data['draws'] = ''; }
	$data['points'] = makeSafe($_REQUEST['points']);
		if($data['points'] == empty_lookup_value){ $data['points'] = ''; }
	$data['edited_by'] = parseCode('<%%editorUsername%%>', false);
	$data['selectedID']=makeSafe($selected_id);
	if($_REQUEST['team_logo_remove'] == 1){
		$data['team_logo'] = '';
	}else{
		$data['team_logo'] = PrepareUploadedFile('team_logo', 102400, 'jpg|jpeg|gif|png', false, "");
		if($data['team_logo']) createThumbnail($data['team_logo'], getThumbnailSpecs('teams', 'team_logo', 'tv'));
		if($data['team_logo']) createThumbnail($data['team_logo'], getThumbnailSpecs('teams', 'team_logo', 'dv'));
	}

	// hook: teams_before_update
	if(function_exists('teams_before_update')){
		$args=array();
		if(!teams_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `teams` set       ' . ($data['team_logo']!='' ? "`team_logo`='{$data['team_logo']}'" : ($_REQUEST['team_logo_remove'] != 1 ? '`team_logo`=`team_logo`' : '`team_logo`=NULL')) . ', `team_name`=' . (($data['team_name'] !== '' && $data['team_name'] !== NULL) ? "'{$data['team_name']}'" : 'NULL') . ', `school`=' . (($data['school'] !== '' && $data['school'] !== NULL) ? "'{$data['school']}'" : 'NULL') . ', `matches`=' . (($data['matches'] !== '' && $data['matches'] !== NULL) ? "'{$data['matches']}'" : 'NULL') . ', `wins`=' . (($data['wins'] !== '' && $data['wins'] !== NULL) ? "'{$data['wins']}'" : 'NULL') . ', `losses`=' . (($data['losses'] !== '' && $data['losses'] !== NULL) ? "'{$data['losses']}'" : 'NULL') . ', `draws`=' . (($data['draws'] !== '' && $data['draws'] !== NULL) ? "'{$data['draws']}'" : 'NULL') . ', `points`=' . (($data['points'] !== '' && $data['points'] !== NULL) ? "'{$data['points']}'" : 'NULL') . ', `edited_by`=' . "'{$data['edited_by']}'" . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="teams_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: teams_after_update
	if(function_exists('teams_after_update')){
		$res = sql("SELECT * FROM `teams` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!teams_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='teams' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function teams_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('teams');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_school = thisOr(undo_magic_quotes($_REQUEST['filterer_school']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: school
	$combo_school = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='teams' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='teams' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `teams` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'teams_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_school->SelectedData = $row['school'];
	}else{
		$combo_school->SelectedData = $filterer_school;
	}
	$combo_school->HTML = '<span id="school-container' . $rnd1 . '"></span><input type="hidden" name="school" id="school' . $rnd1 . '" value="' . html_attr($combo_school->SelectedData) . '">';
	$combo_school->MatchText = '<span id="school-container-readonly' . $rnd1 . '"></span><input type="hidden" name="school" id="school' . $rnd1 . '" value="' . html_attr($combo_school->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_school__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['school'] : $filterer_school); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(school_reload__RAND__) == 'function') school_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function school_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#school-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_school__RAND__.value, t: 'teams', f: 'school' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="school"]').val(resp.results[0].id);
							$j('[id=school-container-readonly__RAND__]').html('<span id="school-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=schools_view_parent]').hide(); }else{ $j('.btn[id=schools_view_parent]').show(); }


							if(typeof(school_update_autofills__RAND__) == 'function') school_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'teams', f: 'school' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_school__RAND__.value = e.added.id;
				AppGini.current_school__RAND__.text = e.added.text;
				$j('[name="school"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=schools_view_parent]').hide(); }else{ $j('.btn[id=schools_view_parent]').show(); }


				if(typeof(school_update_autofills__RAND__) == 'function') school_update_autofills__RAND__();
			});

			if(!$j("#school-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_school__RAND__.value, t: 'teams', f: 'school' },
					success: function(resp){
						$j('[name="school"]').val(resp.results[0].id);
						$j('[id=school-container-readonly__RAND__]').html('<span id="school-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=schools_view_parent]').hide(); }else{ $j('.btn[id=schools_view_parent]').show(); }

						if(typeof(school_update_autofills__RAND__) == 'function') school_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_school__RAND__.value, t: 'teams', f: 'school' },
				success: function(resp){
					$j('[id=school-container__RAND__], [id=school-container-readonly__RAND__]').html('<span id="school-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=schools_view_parent]').hide(); }else{ $j('.btn[id=schools_view_parent]').show(); }

					if(typeof(school_update_autofills__RAND__) == 'function') school_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/teams_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/teams_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Team details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return teams_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return teams_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return teams_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#team_logo').replaceWith('<div class=\"form-control-static\" id=\"team_logo\">' + (jQuery('#team_logo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#team_name').replaceWith('<div class=\"form-control-static\" id=\"team_name\">' + (jQuery('#team_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#school').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#school_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#matches').replaceWith('<div class=\"form-control-static\" id=\"matches\">' + (jQuery('#matches').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#wins').replaceWith('<div class=\"form-control-static\" id=\"wins\">' + (jQuery('#wins').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#losses').replaceWith('<div class=\"form-control-static\" id=\"losses\">' + (jQuery('#losses').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#draws').replaceWith('<div class=\"form-control-static\" id=\"draws\">' + (jQuery('#draws').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#points').replaceWith('<div class=\"form-control-static\" id=\"points\">' + (jQuery('#points').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(school)%%>', $combo_school->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(school)%%>', $combo_school->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(school)%%>', urlencode($combo_school->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'school' => array('schools', 'School'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(team_logo)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=102400>'.$Translation['upload image'].' <input type="file" name="team_logo" id="team_logo">'), $templateCode);
	if($AllowUpdate && $row['team_logo'] != ''){
		$templateCode = str_replace('<%%REMOVEFILE(team_logo)%%>', '<br><input type="checkbox" name="team_logo_remove" id="team_logo_remove" value="1"> <label for="team_logo_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode = str_replace('<%%REMOVEFILE(team_logo)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(team_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(school)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(matches)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(wins)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(losses)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(draws)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(points)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(edited_by)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$row['team_logo'] = ($row['team_logo'] != '' ? $row['team_logo'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(team_logo)%%>', safe_html($urow['team_logo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(team_logo)%%>', html_attr($row['team_logo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(team_logo)%%>', urlencode($urow['team_logo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(team_name)%%>', safe_html($urow['team_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(team_name)%%>', html_attr($row['team_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(team_name)%%>', urlencode($urow['team_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(school)%%>', safe_html($urow['school']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(school)%%>', html_attr($row['school']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(school)%%>', urlencode($urow['school']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(matches)%%>', safe_html($urow['matches']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(matches)%%>', html_attr($row['matches']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(matches)%%>', urlencode($urow['matches']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(wins)%%>', safe_html($urow['wins']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(wins)%%>', html_attr($row['wins']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(wins)%%>', urlencode($urow['wins']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(losses)%%>', safe_html($urow['losses']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(losses)%%>', html_attr($row['losses']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(losses)%%>', urlencode($urow['losses']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(draws)%%>', safe_html($urow['draws']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(draws)%%>', html_attr($row['draws']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(draws)%%>', urlencode($urow['draws']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(points)%%>', safe_html($urow['points']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(points)%%>', html_attr($row['points']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(points)%%>', urlencode($urow['points']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', safe_html($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(edited_by)%%>', safe_html($urow['edited_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(edited_by)%%>', urlencode($urow['edited_by']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(team_logo)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(team_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(team_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(school)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(school)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(matches)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(matches)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(wins)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(wins)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(losses)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(losses)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(draws)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(draws)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(points)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(points)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(edited_by)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(edited_by)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('teams');
	if($selected_id){
		$jdata = get_joined_record('teams', $selected_id);
		if($jdata === false) $jdata = get_defaults('teams');
		$rdata = $row;
	}
	$templateCode .= loadView('teams-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: teams_dv
	if(function_exists('teams_dv')){
		$args=array();
		teams_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>