<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/test2.php");
	include("$currDir/test2_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('test2');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "test2";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`test2`.`id`" => "id",
		"`test2`.`field1`" => "field1",
		"`test2`.`field2`" => "field2",
		"`test2`.`field3`" => "field3",
		"`test2`.`created_by`" => "created_by"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`test2`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`test2`.`id`" => "id",
		"`test2`.`field1`" => "field1",
		"`test2`.`field2`" => "field2",
		"`test2`.`field3`" => "field3",
		"`test2`.`created_by`" => "created_by"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`test2`.`id`" => "ID",
		"`test2`.`field1`" => "Field1",
		"`test2`.`field2`" => "Field2",
		"`test2`.`field3`" => "Field3",
		"`test2`.`created_by`" => "Created by"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`test2`.`id`" => "id",
		"`test2`.`field1`" => "field1",
		"`test2`.`field2`" => "field2",
		"`test2`.`field3`" => "field3",
		"`test2`.`created_by`" => "created_by"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`test2` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "test2_view.php";
	$x->RedirectAfterInsert = "test2_view.php?SelectedID=#ID#";
	$x->TableTitle = "Test2";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`test2`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("Field1", "Field2", "Field3", "Created by");
	$x->ColFieldName = array('field1', 'field2', 'field3', 'created_by');
	$x->ColNumber  = array(2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/test2_templateTV.html';
	$x->SelectedTemplate = 'templates/test2_templateTVS.html';
	$x->TemplateDV = 'templates/test2_templateDV.html';
	$x->TemplateDVP = 'templates/test2_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `test2`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='test2' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `test2`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='test2' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`test2`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: test2_init
	$render=TRUE;
	if(function_exists('test2_init')){
		$args=array();
		$render=test2_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: test2_header
	$headerCode='';
	if(function_exists('test2_header')){
		$args=array();
		$headerCode=test2_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: test2_footer
	$footerCode='';
	if(function_exists('test2_footer')){
		$args=array();
		$footerCode=test2_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>